/**
 * Build misty-morning's runtime artifacts from the authored sources.
 *
 *   src/palette.mjs     colour schemes + `--dsw-*` token tables
 *   src/theme.css       the plugin stylesheet (references `--dmm-*`)
 *   src/client-body.js  the browser-half plugin body
 *   src/index.js        the host half
 *   assets/artwork.jpg  the source illustration
 *
 * Outputs:
 *   lib/index.js   host half (verbatim copy)
 *   lib/client.js  one `window.__ModuleLoader__.load({...})` bundle carrying
 *                  the token tables, the data-URI artwork, and the body
 *
 * Options:
 *   --background-scope <workspace|home>  where the illustration appears
 *                                        (default: workspace, matching the
 *                                        source theme's own contract)
 *   --no-motes                           drop the ambient light-mote pattern on
 *                                        the home stage entirely
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { paletteVariables, tokens } from '../src/palette.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')

const argv = process.argv.slice(2)
const flagIndex = argv.indexOf('--background-scope')
const backgroundScope = flagIndex === -1 ? 'workspace' : argv[flagIndex + 1]
const noMotes = argv.includes('--no-motes')
if (backgroundScope !== 'workspace' && backgroundScope !== 'home') {
  throw new Error(`--background-scope must be "workspace" or "home", got "${backgroundScope}"`)
}

/** Body selector the artwork canvas is painted on. */
const ART_SCOPE = backgroundScope === 'home'
  ? 'body:has([data-dsh-center-col] [data-phase="hero"])'
  : 'body'

const PLUGIN_ID = 'dsh-theme-misty-morning'

/** Emit one scheme block of `--dmm-*` custom properties. */
function paletteBlock(selector, scheme, artUrl) {
  const variables = { ...paletteVariables(scheme, artUrl) }
  if (noMotes) variables['--dmm-motes'] = 'none'
  const entries = Object.entries(variables)
    .map(([name, value]) => `  ${name}: ${value};`)
  return `${selector} {\n${entries.join('\n')}\n}`
}

/** Assert the two token tables describe the same token set. */
function assertTokenParity(light, dark) {
  const lightNames = new Set(Object.keys(light))
  const darkNames = new Set(Object.keys(dark))
  const missingInDark = [...lightNames].filter((name) => !darkNames.has(name))
  const missingInLight = [...darkNames].filter((name) => !lightNames.has(name))
  if (missingInDark.length > 0 || missingInLight.length > 0) {
    throw new Error(
      `token tables disagree: missing dark ${JSON.stringify(missingInDark)}, `
      + `missing light ${JSON.stringify(missingInLight)}`,
    )
  }
}

async function main() {
  assertTokenParity(tokens.light, tokens.dark)
  const artwork = await readFile(join(root, 'assets', 'artwork.jpg'))
  const artUrl = `data:image/jpeg;base64,${artwork.toString('base64')}`

  const rules = await readFile(join(root, 'src', 'theme.css'), 'utf8')
  const css = [
    '/* Generated by scripts/build.mjs — edit src/palette.mjs and src/theme.css. */',
    paletteBlock('body', 'light', artUrl),
    '',
    paletteBlock('body[data-ds-dark-theme]', 'dark', artUrl),
    '',
    rules.replaceAll('__ART_SCOPE__', ART_SCOPE),
  ].join('\n')

  const body = await readFile(join(root, 'src', 'client-body.js'), 'utf8')

  const bundle = `window.__ModuleLoader__.load({
	id: ${JSON.stringify(PLUGIN_ID)},
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		var PLUGIN_ID = ${JSON.stringify(PLUGIN_ID)};
		var LIGHT_TOKENS = ${JSON.stringify(tokens.light, null, 2)};
		var DARK_TOKENS = ${JSON.stringify(tokens.dark, null, 2)};
		var THEME_CSS = ${JSON.stringify(css)};
${body.split('\n').map((line) => (line.length > 0 ? `\t\t${line}` : line)).join('\n')}
		return module.exports;
	}
});
`

  await mkdir(join(root, 'lib'), { recursive: true })
  await writeFile(join(root, 'lib', 'client.js'), bundle)
  await writeFile(join(root, 'lib', 'index.js'), await readFile(join(root, 'src', 'index.js'), 'utf8'))

  process.stdout.write(
    `misty-morning: built lib/client.js (${bundle.length} bytes, `
    + `${Object.keys(tokens.light).length} token overrides, scope=${backgroundScope}`
    + `${noMotes ? ', motes=off' : ''})\n`,
  )
}

await main()
